name: Surge Deployment Github Actions
on: [push, pull_request]
jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      # Use GitHub Actions' cache to shorten build times and decrease load on servers
   
      # Deployment to surge:
      - name: Install surge and fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: npm install -g surge
      - run: surge ./ ${{secrets.SURGE_SITE}} --token ${{ secrets.SURGE_TOKEN }}
